import type { Expression } from './types';

export const EXPRESSIONS: Expression[] = [
  {
    id: 'brush-it-off',
    term: 'brush it off',
    meaning: '별일 아닌 듯 넘기다, 툭툭 털어내다',
    register: '구어체',
    example: '“She brushed it off, but I could tell it stayed with her.”',
    bookId: 'klara',
    page: 132,
    askedOn: '2026-08-23',
    askedLabel: '어제',
    status: '헷갈려요',
    confusedWith: {
      expressionId: 'shrug-off',
      note: 'shrug off는 어깨를 으쓱하는 무관심에 가깝고, brush off는 손으로 털어내듯 상대의 말을 흘려보내는 쪽이에요.',
    },
  },
  {
    id: 'for-the-time-being',
    term: 'for the time being',
    meaning: '당분간은, 지금으로서는',
    register: '중립',
    example: '“For the time being, we kept the blinds down.”',
    bookId: 'klara',
    page: 132,
    askedOn: '2026-08-23',
    askedLabel: '어제',
    status: '헷갈려요',
  },
  {
    id: 'make-out',
    term: 'make out',
    meaning: '겨우 알아보다, 분간하다',
    register: '중립',
    example: '“I could just make out the Sun’s pattern on the far wall.”',
    bookId: 'klara',
    page: 133,
    askedOn: '2026-08-23',
    askedLabel: '어제',
    status: '헷갈려요',
  },
  {
    id: 'shrug-off',
    term: 'shrug off',
    meaning: '대수롭지 않게 여기다, 무시해 버리다',
    register: '구어체',
    example: '“He shrugged off the question and turned to the window.”',
    bookId: 'remains',
    page: 74,
    askedOn: '2026-02-18',
    askedLabel: '2월 18일',
    status: '외웠어요',
    confusedWith: {
      expressionId: 'brush-it-off',
      note: '6개월 뒤 Klara에서 brush it off를 만나며 다시 헷갈렸어요.',
    },
  },
  {
    id: 'put-up-with',
    term: 'put up with',
    meaning: '참고 견디다',
    register: '구어체',
    example: '“I had put up with the noise for the better part of a year.”',
    bookId: 'normal-people',
    page: 58,
    askedOn: '2026-06-04',
    askedLabel: '6월 4일',
    status: '외웠어요',
  },
  {
    id: 'come-to-terms-with',
    term: 'come to terms with',
    meaning: '받아들이게 되다, 마음으로 정리하다',
    register: '문어체',
    example: '“It took him years to come to terms with what he had chosen.”',
    bookId: 'remains',
    page: 191,
    askedOn: '2026-07-12',
    askedLabel: '7월 12일',
    status: '헷갈려요',
  },
  {
    id: 'the-better-part-of',
    term: 'the better part of',
    meaning: '~의 대부분, 거의 ~ 내내',
    register: '문어체',
    example: '“We spent the better part of the evening in silence.”',
    bookId: 'small-things',
    page: 41,
    askedOn: '2026-08-11',
    askedLabel: '8월 11일',
    status: '헷갈려요',
  },
  {
    id: 'take-after',
    term: 'take after',
    meaning: '(부모를) 닮다',
    register: '중립',
    example: '“She takes after her mother in that respect.”',
    bookId: 'normal-people',
    page: 120,
    askedOn: '2026-05-29',
    askedLabel: '5월 29일',
    status: '외웠어요',
  },
];

export const expressionById = (id: string) =>
  EXPRESSIONS.find((e) => e.id === id);
